on:
  push:
    branches:
      - main

jobs:
  LambdaCI:
    name: 'lambda CI'
    runs-on: ubuntu
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: install npm
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: build artifacts
      run: | 
        apt install zip -y
        zip health.zip health.py

    - name: S3 upload
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: s3 cp health.zip s3://${{ vars.BUCKET_NAME }}/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
